### ISSUE TITLE
Modules are not idempotent in rootless mode

### ISSUE THREAD

**Issue by waweber** [containers/ansible-podman-collections#212]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

The `podman_*` modules appear to remove and recreate identical resources when running in rootless mode.

**Steps to reproduce the issue:**

1. Create a non-privileged system user

2. Create a task to create a podman resource as your system user, e.g.
```
    - name: Set up www network
      containers.podman.podman_network:
        name: www-network
        state: present
        recreate: no
        debug: yes
      become: yes
      become_user: testuser
```

3. Run your playbook again, and see that the resource is dropped and recreated. This appears to happen for networks, pods, and containers, at least.

**Describe the results you received:**

The resources are deleted and recreated.

**Describe the results you expected:**

The task should have passed "ok" with no changes.

**Additional information you deem important (e.g. issue happens only occasionally):**

Here's some output from the create/recreate:

```changed: [example1] => {"actions": ["created www-network"], "changed": true, "network": {"cniVersion": "0.4.0", "name": "www-network", "plugins": [{"bridge": "cni-podman0", "hairpinMode": true, "ipMasq": true, "ipam": {"ranges": [[{"gateway": "10.88.2.1", "subnet": "10.88.2.0/24"}]], "routes": [{"dst": "0.0.0.0/0"}], "type": "host-local"}, "isGateway": true, "type": "bridge"}, {"capabilities": {"portMappings": true}, "type": "portmap"}, {"backend": "", "type": "firewall"}, {"type": "tuning"}, {"capabilities": {"aliases": true}, "domainName": "dns.podman", "type": "dnsname"}]}, "podman_actions": ["podman network create www-network"], "podman_version": "3.0.0-dev", "stderr": "time=\"2021-02-27T03:21:56Z\" level=warning msg=\"Failed to add podman to systemd sandbox cgroup: exec: \\\"dbus-launch\\\": executable file not found in $PATH\"\n", "stderr_lines": ["time=\"2021-02-27T03:21:56Z\" level=warning msg=\"Failed to add podman to systemd sandbox cgroup: exec: \\\"dbus-launch\\\": executable file not found in $PATH\""], "stdout": "/home/testuser/.config/cni/net.d/www-network.conflist\n", "stdout_lines": ["/home/testuser/.config/cni/net.d/www-network.conflist"]}`

```changed: [example1] => {"actions": ["recreated www-network"], "changed": true, "network": {"cniVersion": "0.4.0", "name": "www-network", "plugins": [{"bridge": "cni-podman0", "hairpinMode": true, "ipMasq": true, "ipam": {"ranges": [[{"gateway": "10.88.2.1", "subnet": "10.88.2.0/24"}]], "routes": [{"dst": "0.0.0.0/0"}], "type": "host-local"}, "isGateway": true, "type": "bridge"}, {"capabilities": {"portMappings": true}, "type": "portmap"}, {"backend": "", "type": "firewall"}, {"type": "tuning"}, {"capabilities": {"aliases": true}, "domainName": "dns.podman", "type": "dnsname"}]}, "podman_actions": ["podman network rm -f www-network", "podman network create www-network"], "podman_version": "3.0.0-dev", "stderr": "time=\"2021-02-27T03:24:24Z\" level=warning msg=\"Failed to add podman to systemd sandbox cgroup: exec: \\\"dbus-launch\\\": executable file not found in $PATH\"\n", "stderr_lines": ["time=\"2021-02-27T03:24:24Z\" level=warning msg=\"Failed to add podman to systemd sandbox cgroup: exec: \\\"dbus-launch\\\": executable file not found in $PATH\""], "stdout": "/home/testuser/.config/cni/net.d/www-network.conflist\n", "stdout_lines": ["/home/testuser/.config/cni/net.d/www-network.conflist"]}```

Ignore the cgroup warning (maybe), that does not happen on my default account and the issue is still present.

**Output of `ansible --version`:**

ansible 2.10.5

**Output of `podman version`:**

podman version 3.0.0-dev

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.19.2
  cgroupManager: cgroupfs
  cgroupVersion: v1
  conmon:
    package: conmon-2.0.25-1.module_el8.4.0+673+eabfc99d.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.25, commit: 897f4ebd69b9e9c725621fabf1d7c918ef635a68'
  cpus: 1
  distribution:
    distribution: '"centos"'
    version: "8"
  eventLogger: file
  hostname: localhost.localdomain
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 990
      size: 1
    uidmap:
    - container_id: 0
      host_id: 994
      size: 1
  kernel: 4.18.0-277.el8.x86_64
  linkmode: dynamic
  memFree: 45039616
  memTotal: 487579648
  ociRuntime:
    name: crun
    package: crun-0.17-1.module_el8.4.0+673+eabfc99d.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 0.17
      commit: 0e9229ae34caaebcb86f1fde18de3acaf18c6d9a
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +YAJL
  os: linux
  remoteSocket:
    path: /tmp/podman-run-994/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_NET_RAW,CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    selinuxEnabled: true
  slirp4netns:
    executable: /bin/slirp4netns
    package: slirp4netns-1.1.8-1.module_el8.4.0+641+6116a774.x86_64
    version: |-
      slirp4netns version 1.1.8
      commit: d361001f495417b880f20329121e3aa431a8f90f
      libslirp: 4.3.1
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.4.3
  swapFree: 2076053504
  swapTotal: 2147479552
  uptime: 1h 36m 36.45s (Approximately 0.04 days)
registries:
  search:
  - registry.access.redhat.com
  - registry.redhat.io
  - docker.io
store:
  configFile: /home/testuser/.config/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions:
    overlay.mount_program:
      Executable: /bin/fuse-overlayfs
      Package: fuse-overlayfs-1.4.0-2.module_el8.4.0+673+eabfc99d.x86_64
      Version: |-
        fusermount3 version: 3.2.1
        fuse-overlayfs: version 1.4
        FUSE library version 3.2.1
        using FUSE kernel interface version 7.26
  graphRoot: /home/testuser/.local/share/containers/storage
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 0
  runRoot: /tmp/podman-run-994/containers
  volumePath: /home/testuser/.local/share/containers/storage/volumes
version:
  APIVersion: 3.0.0
  Built: 1612303593
  BuiltTime: Tue Feb  2 22:06:33 2021
  GitCommit: ""
  GoVersion: go1.15.7
  OsArch: linux/amd64
  Version: 3.0.0-dev
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-3.0.0-0.33rc2.module_el8.4.0+673+eabfc99d.x86_64
```

**Playbok you run with ansible (e.g. content of `playbook.yaml`):**

```
- name: Configure podman resources
  hosts:
    - example
  tasks:
    - name: Set up www network
      containers.podman.podman_network:
        name: www-network
        state: present
        recreate: no
        debug: yes
      become_user: testuser
```

**Command line and output of ansible run with high verbosity:**

```
ansible-playbook -i inventory.yml config.yml -vv

changed: [example1] => {"actions": ["recreated www-network"], "changed": true, "network": {"cniVersion": "0.4.0", "name": "www-network", "plugins": [{"bridge": "cni-podman0", "hairpinMode": true, "ipMasq": true, "ipam": {"ranges": [[{"gateway": "10.88.2.1", "subnet": "10.88.2.0/24"}]], "routes": [{"dst": "0.0.0.0/0"}], "type": "host-local"}, "isGateway": true, "type": "bridge"}, {"capabilities": {"portMappings": true}, "type": "portmap"}, {"backend": "", "type": "firewall"}, {"type": "tuning"}, {"capabilities": {"aliases": true}, "domainName": "dns.podman", "type": "dnsname"}]}, "podman_actions": ["podman network rm -f www-network", "podman network create www-network"], "podman_version": "3.0.0-dev", "stderr": "time=\"2021-02-27T03:41:37Z\" level=warning msg=\"Failed to add podman to systemd sandbox cgroup: exec: \\\"dbus-launch\\\": executable file not found in $PATH\"\n", "stderr_lines": ["time=\"2021-02-27T03:41:37Z\" level=warning msg=\"Failed to add podman to systemd sandbox cgroup: exec: \\\"dbus-launch\\\": executable file not found in $PATH\""], "stdout": "/home/testuser/.config/cni/net.d/www-network.conflist\n", "stdout_lines": ["/home/testuser/.config/cni/net.d/www-network.conflist"]}
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

In a virtualbox

**Comment by sshnaidm** [comment]
@waweber can you please run `ansible-playbook` with `--diff` option? Like `ansible-playbook -vvvv --diff playbook.yml`. I can't reproduce it currently.

**Comment by waweber** [comment]
@sshnaidm here's an entire minimal ansible setup, along with the Vagrantfile I used, and the log output
[example.tar.gz](https://github.com/containers/ansible-podman-collections/files/6055221/example.tar.gz)

**Comment by sshnaidm** [comment]
@waweber can you try version from master please? I think it should help, most of issues were solved.

**Comment by waweber** [comment]
I updated to the latest master, the issue still happens.

I still notice this "disable dns" setting mentioned in the diff, I'm assuming the current state doesn't get parsed correctly somehow?

```
--- before
+++ after
@@ -1 +1 @@
-disable_dns - False
+disable_dns - True

changed: [test] => {
    "actions": [
        "recreated www-network"
    ],
    "changed": true,
    "diff": {
        "after": "disable_dns - True\n",
        "before": "disable_dns - False\n"
    },
    "invocation": {
        "module_args": {
            "debug": true,
            "disable_dns": null,
            "driver": null,
            "executable": "podman",
            "gateway": null,
            "internal": null,
            "ip_range": null,
            "ipv6": null,
            "macvlan": null,
            "name": "www-network",
            "opt": null,
            "recreate": false,
            "state": "present",
            "subnet": null
        }
    },
    "network": {
        "cniVersion": "0.4.0",
        "name": "www-network",
        "plugins": [
            {
                "bridge": "cni-podman0",
                "hairpinMode": true,
                "ipMasq": true,
                "ipam": {
                    "ranges": [
                        [
                            {
                                "gateway": "10.88.2.1",
                                "subnet": "10.88.2.0/24"
                            }
                        ]
                    ],
                    "routes": [
                        {
                            "dst": "0.0.0.0/0"
                        }
                    ],
                    "type": "host-local"
                },
                "isGateway": true,
                "type": "bridge"
            },
            {
                "capabilities": {
                    "portMappings": true
                },
                "type": "portmap"
            },
            {
                "backend": "",
                "type": "firewall"
            },
            {
                "type": "tuning"
            },
            {
                "capabilities": {
                    "aliases": true
                },
                "domainName": "dns.podman",
                "type": "dnsname"
            }
        ]
    },
    "podman_actions": [
        "podman network rm -f www-network",
        "podman network create www-network"
    ],
    "podman_version": "3.0.0-dev",
    "stderr": "time=\"2021-03-01T16:10:15Z\" level=warning msg=\"Failed to add podman to systemd sandbox cgroup: exec: \\\"dbus-launch\\\": executable file not found in $PATH\"\n",
    "stderr_lines": [
        "time=\"2021-03-01T16:10:15Z\" level=warning msg=\"Failed to add podman to systemd sandbox cgroup: exec: \\\"dbus-launch\\\": executable file not found in $PATH\""
    ],
    "stdout": "/home/testuser/.config/cni/net.d/www-network.conflist\n",
    "stdout_lines": [
        "/home/testuser/.config/cni/net.d/www-network.conflist"
    ]
}
```

**Comment by waweber** [comment]
This particular issue seems to be coming from https://github.com/containers/ansible-podman-collections/blob/7bacd62fadb2bbc7f2bde842d15aa7f89c390a97/plugins/modules/podman_network.py#L311

I am not explicitly specifying `disable_dns: yes`, but I assume what I want here is "no." It looks like it is looking for a file to check whether or not the dnsname plugin is installed, but none of these exist and I think it is in fact installed (running `curl http://othercontainername` works). Running `find / | grep -i dnsname` in this VM gives me no files, so maybe looking for the plugin file isn't always reliable

**Comment by sshnaidm** [comment]
@waweber in your log network `www-network` already existed. Can you please run the following playbook?

```
- hosts: all
  tasks:

    - name: Delete www network if exists
      containers.podman.podman_network:
        name: www-network
        state: absent

    - name: Set up new www network
      containers.podman.podman_network:
        name: www-network
        state: present
        debug: true

    - name: Run again setup of www network
      containers.podman.podman_network:
        name: www-network
        state: present
        debug: true
```
Yes, it's related to DNS plugin finding, so I want to be sure.
Do you have one of these files on your remote system?
```
'/usr/libexec/cni/dnsname',
'/usr/lib/cni/dnsname',
'/opt/cni/bin/dnsname',
'/opt/bridge/bin/dnsname'
```

**Comment by sshnaidm** [comment]
@waweber actually nevermind, I could reproduce the issue on CentOS 8. Seems like it appears there only. Will work to fix it, thanks for reporting.

**Comment by sshnaidm** [comment]
Seems like rootless network will always has DNS enabled. But need somehow to detect that it's rootless.

**Comment by waweber** [comment]
Also noteworthy is that if I do make the network as root, it doesn't enable DNS. Trying to explicitly set `disable_dns: no` results in the diff:

```
--- before
+++ after
@@ -1 +1 @@
-disable_dns - True
+disable_dns - False
```

every time. The dns plugin is definitely available as it works in usermode.

**Comment by waweber** [comment]
@sshnaidm looked into this some more and found some interesting stuff

So it turns out, the `dnsname` executable is not present in the `containernetworking-plugins` package that gets installed as a dependency for `podman`. This is instead provided by `podman-plugins`, which was not installed on the systems I tested with.

However, container name resolution was working somehow when running rootless. The plugin was clearly not installed on the host system, so I don't know what was providing this functionality.

CentOS 8/Stream and rootless podman is in a bit of a sorry state at the moment as well, so it is difficult to tell if a feature is working or not.
